
export const ADDRESS_REQ = 'ADDRESS_REQ';
export const ADDRESS_GET_SUCCESS = 'ADDRESS_GET_SUCCESS';
export const ADDRESS_FAILURE = 'ADDRESS_FAILURE';

export const ADD_NEW_ADDRESS = 'ADD_NEW_ADDRESS';

export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';


