
export const CART_REQ = 'CART_REQ';
export const CART_REQ_SUCCESS = 'CART_REQ_SUCCESS';
export const CART_REQ_FAILURE = 'CART_REQ_FAILURE';

// POST 

export const CART_POST_SUCCESS = 'CART_POST_SUCCESS';

// PATCH

export const CART_UPDATE_SUCCESS = 'CART_UPDATE_SUCCESS';

export const CART_DELETE_SUCCESS = 'CART_DELETE_SUCCESS';

