

export const PROFILE_REQ = 'PROFILE_REQ';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const PROFILE_REQ_FAILURE = 'PROFILE_REQ_FAILURE';

export const ADD_PROFILE_SUCCESS = 'ADD_PROFILE_SUCCESS';

export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';