
export const ORDER_REQ = 'ORDER_REQ';
export const ORDER_REQ_SUCCESS = 'ORDER_REQ_SUCCESS';
export const ORDER_REQ_FAILURE = 'ORDER_REQ_FAILURE';

export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';

