
export const PRODUCT_REQ = 'PRODUCT_REQ';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_FAILURE = 'PRODUCT_FAILURE';

export const GET_WISHLIST_PRODUCTS = "GET_WISHLIST_PRODUCTS"
export const ADD_WISHLIST_PRODUCTS = "GET_WISHLIST_PRODUCTS"
export const ADD_WISHLIST_PRODUCTS_SUCCESS = "ADD_WISHLIST_PRODUCTS_SUCCESS"
export const ADD_WISHLIST_PRODUCTS_FAILURE = "ADD_WISHLIST_PRODUCTS_FAILURE"
export const DELETE_WISHLIST_PRODUCTS = "DELETE_WISHLIST_PRODUCTS"
